version: 2

project_name: pgpeek

before:
  hooks:
    - go mod tidy

builds:
  - id: pgpeek
    main: .
    binary: pgpeek
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

kos:
  - id: pgpeek
    build: pgpeek
    main: .
    base_image: gcr.io/distroless/static-debian12:nonroot
    repositories:
      - ghcr.io/descope/pgpeek
    platforms:
      - linux/amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    bare: true
    preserve_import_paths: false
    sbom: spdx

archives:
  - id: pgpeek
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive

changelog:
  disable: true

release:
  github:
    owner: descope
    name: pgpeek
  mode: append
